#!/bin/sh
# ------------------------------------------------------------
# Grep some nasty strings in the delivered header and example
# files.
# Usage: launch util/checkDeliveryFiles from sim root.
# ------------------------------------------------------------

GRAPHDIR=.

touch FILES.tmp
rm -f FILES.tmp
cat ${GRAPHDIR}/util/TarZ/USERFILES ${GRAPHDIR}/util/TarZ/USERBIN.cpp > FILES.tmp
for f in `cat FILES.tmp`
do
    echo "--------------------------"
    echo $f:
    grep -i "bug" ${GRAPHDIR}/${f} | grep -v "debugInfo" | grep -v -i "debug mode" | grep -v "ILCDEBUG" | grep -v "ILCULTRADEBUG" | grep "debug("
    grep -i "not yet implemented" ${GRAPHDIR}/${f}
    grep -i "nyi" ${GRAPHDIR}/${f}
    grep -i "todo" ${GRAPHDIR}/${f}
    grep -i "phl" ${GRAPHDIR}/${f}
    grep "XNO" ${GRAPHDIR}/${f}
    grep "PM" ${GRAPHDIR}/${f}
    grep "CB" ${GRAPHDIR}/${f} | grep -v "ILCB"
    grep "PC" ${GRAPHDIR}/${f} 
    grep "WN" ${GRAPHDIR}/${f} 
    grep -i "jerome" ${GRAPHDIR}/${f} 
    grep -i "rogerie" ${GRAPHDIR}/${f} 
    grep -i "laborie" ${GRAPHDIR}/${f} 
    grep -i "wait" ${GRAPHDIR}/${f} 
    grep -i "not available" ${GRAPHDIR}/${f} 
    grep -i "delayed" ${GRAPHDIR}/${f} 
    grep -i "obsolete" ${GRAPHDIR}/${f} 
    grep -i "warning" ${GRAPHDIR}/${f}
    grep -i "question" ${GRAPHDIR}/${f}
    grep -i "dummy" ${GRAPHDIR}/${f}
done	
rm -f FILES.tmp
