if (typeof WEBSIGNIN == "undefined" || WEBSIGNIN == null) var WEBSIGNIN = {};
WEBSIGNIN.registerData={"title":"IBM registration",
	"intro":"Sign in below and choose a location.",
	"confirmation":"You have successfully created an IBM user account and will be automatically logged in within 10 seconds",
	"register":{"fields":{"emailAddress":"Email address:",
	"password":"Password:",
	"confirmPassword":"Re-enter password:",
	"securityQuestion":"Security question:",
	"securityAnswer":"Answer to security question:",
	"country":"Country of residence:",
	"language":"Language:",
	"firstName":"First name:",
	"lastName":"Last name:"}},
	"privacy":{"name":"Privacy policy","link":"//www.ibm.com/privacy"},
	"helpID":{"name":"Help with IDs and passwords?","link":" "},
	"editInfo":{"name":"Previous","link":" "},
	"editRevised":"Previous",
	"step1of2":"Step 1 of 2",
	"step2of2":"Step 2 of 2",
	"requiredfields":"Required fields are indicated with an asterisk",
	"backout1":"Asterisks",
	"backout2":"indicate fields required to complete this transaction.",
	"continuenextpage":"Continue to the next page to complete your registration.",
	"security":"All information submitted is secure.",
	"thisdataatanyTimeRevocablebyYou":"This data, at any time revocable by you, may be stored by IBM or an affiliate on an international server and used by IBM or an affiliate.",
	"emailIBMproducts":"E-mail: Stay informed about IBM products, services, and other offerings! If you want to stay informed by e-mail, please let us know by checking the box below.","emailYes":"E-mail: Yes, please have IBM or an affiliate send me e-mail.","otherCommunication":"Other communications: IBM or an affiliate or selected organizations may keep you informed about IBM related products, services and other offerings through ways other than e-mail, for example, by telephone or postal mail. If you do not want us to use the information you provided here to keep you informed through other ways, please indicate in the box below.",
	"otherCommunicationPleaseDoNotUseTheInformation":"Other communications: Please do not use the information I have provided here.",
	"byClickingSubmit":"By clicking 'submit', you agree that IBM may process your data in the manner indicated above and as described in our",
	"willibmID":"(Will be your IBM ID)","charsmin":"(8 Characters min)",
	"helpIDsandPw":"Help with IDs and passwords?",
	"helptooltipline1":"Your IBM ID must have the format of a valid email address. It is uneditable and ",
	"helptooltipline2":"must be no longer than 80 characters",
	"helptooltipline3":"must contain an '@' character that separates the user and domain values (example: lorem@ipsum.com)",
	"helptooltipline4":"must be composed of at least two sub-domains separated by a '.' (example: ibm.com)",
	"helptooltipline5":"may contain numbers (0-9), upper and lower case letters (A-Z, a-z), hyphens (-), underscore (_) and periods (.), !, #, $, %, &, ', +, /, =, ?, [, ], ^, `, {, |, }, ~ ",
	"helptooltipline6":"cannot contain any spaces, backslash (\), colon (:), double-quote (\"), semicolon (;), comma (,), less than (<) and the greater than (>) characters, parentheses(\"(\", \")\"), asterisks(\"*\")"
};
WEBSIGNIN.registerButtonData = {"continuebutton":"Continue",
								"cancel":"Cancel",
								"back":"Back",
								"register":"Register",
								"submit":"Submit"};
WEBSIGNIN.errorData={"register":{"requiredError":"Please complete the required field(s) highlighted below to submit your registration information.",
								"invalidError":"We're sorry, the information provided is not valid. Please try again.",
								"passconfirmpassmatch":"You must enter the same password in the password and password confirm fields.",
								"passwordcontainsemail":"We're sorry, the password you have chosen has not been accepted, as it is the same as or contains your IBM ID. Please choose another password."}};

