#!/bin/sh

awk 'BEGIN {
            NL=0
           }
     {
     NL = NL +1;
     if (NL == 1) {
      NJOBS = $1;
      NMACHINES = $2;
      printf("%s %s ", $1, $2);
     }
     else {
         printf("%s %s ", $1, $2);
       }     
     if (NF == 0)
       printf(" \n");
     }
     END{
printf("\n");
}
' $1