#!/bin/tcsh

# log: 000427

# nnc problem generator script

# $1: number of nodes
# $2: number of arcs
# $3: min weight
# $4: max weight
# $5: number of operations
# $6: rnd generator seed
# $7: options m=modifying sequence generation
#             z=initial graph has all zero-length cycles (=> sequences with all increases)
#             d=deep solution structure tree
#             s=shallow solution structure tree

setenv OUT_ROOT ../results
setenv INP_ROOT ../inputs
setenv G_PATH $INP_ROOT/G.nnc.$1.$2.$3.$4.$6.$7
setenv P_PATH $INP_ROOT/P.nnc.$1.$2.$3.$4.$6.$7
setenv S_PATH $INP_ROOT/S.nnc.$1.$2.$3.$4.$5.$6.$7

echo " "
echo "======================="
echo "Generating problem:"
echo "    Nodes:      $1"
echo "    Arcs:       $2"
echo "    Min Weight: $3"
echo "    Max Weight: $4"
echo "    Num Ops:    $5"
echo "    Seed:       $6"
echo "    Options:    $7"

echo "-----------------------"
echo "Generating graph ..."
../bin/gen_graph_rnd_nnc $G_PATH $1 $2 $3 $4 $6 $P_PATH $7

echo "-----------------------"
echo "Generating sequence ..."
../bin/gen_seq_rnd_nnc_dfmn $G_PATH $5 $3 $4 $S_PATH $6 $7 $P_PATH

echo " "
echo "Total increases:"
grep "I" $S_PATH | wc -l

echo " "
echo "Total decreases:"
grep "D" $S_PATH | wc -l
